#!/usr/bin/env bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

"$SBT" transferPublishAndTagResources

scripts/publishAndTag 'slamdata/fs2-ssh'

bumpInDownstream() { echo $1 > fs2-ssh-version; }
export -f bumpInDownstream

scripts/bumpDependentProject slamdata quasar-destination-thoughtspot bumpInDownstream
